project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
preserve_hierarchy: true

files:
  - source: /app/src/main/assets/tips/tips
    translation: /app/src/main/assets/tips/tips-%locale_with_underscore%
    type: hyper_ceiler_tips

  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    type: android
