name: "🐛 Bug"
description: 问题报告.
title: "🐛 [BUG] <问题标题>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "问题描述"
      description: 请输入简洁且明确的问题描述。
      placeholder: ...的...功能出现...异常
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: "模块日志"
      description: LSPosed管理器 - 日志 或 软件崩溃日志
      placeholder: ...
    validations:
      required: true
  - type: textarea
    id: repord
    attributes:
      label: "复现步骤"
      description: 输入简明的问题复现步骤。
      value: |
        1. 前往 '...'
        2. 点击 '....'

        ....
        出现问题
      render: bash
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "问题截图"
      description: 添加问题截图以便我们快速定位.
      value: |
        ![图片注释](图片链接)
    validations:
      required: false
  - type: input
    id: device
    attributes:
      label: "机型"
      description: 填写你的机型，可填型号.
      placeholder: Xiaomi
    validations:
      required: true
  - type: dropdown
    id: miui_version
    attributes:
      label: "MIUI/HyperOS 版本"
      description: 您当前正在使用的 MIUI/HyperOS 版本
      multiple: true
      options:
        - MIUI12 / MIUI12.5
        - MIUI13
        - MIUI14
        - Xiaomi HyperOS 1.0
        - 其它
    validations:
      required: true
  - type: dropdown
    id: android_version
    attributes:
      label: "Android 版本"
      description: 您当前正在使用的 Android 版本
      multiple: true
      options:
        - Android 11
        - Android 12
        - Android 13
        - Android 14
    validations:
      required: true
  - type: input
    id: hyperceiler_version
    attributes:
      label: "HyperCeiler 版本"
      description: 填写您的 HyperCeiler 版本.
      placeholder: x.y.z-YYYYMMDD
    validations:
      required: true
