name: "🐛 Bug"
description: 问题报告.
title: "🐛 [BUG] <问题标题>"
labels: [
  "bug"
]
body:
  - type: textarea
    id: description
    attributes:
      label: "问题描述"
      description: 请输入简洁且明确的问题描述。
      placeholder: ...的...功能出现...异常
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: "模块日志"
      description: LSPosed管理器 - 日志 或 软件崩溃日志
      placeholder: ...
    validations:
      required: true
  - type: textarea
    id: repord
    attributes:
      label: "复现步骤"
      description: 输入简明的问题复现步骤。
      value: |
        1. 前往 '...'
        2. 点击 '....'

        ....
        出现问题
      render: bash
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "问题截图"
      description: 添加问题截图以便我们快速定位.
      value: |
        ![图片注释](图片链接)
    validations:
      required: false
  - type: textarea
    id: device
    attributes:
      label: "HyperCeiler 设备信息"
      description: 请务必上传 HyperCeiler 设置-开发者选项-调试信息 的截图，以便诊断问题.
      value: |
        ![图片注释](图片链接)
    validations:
      required: false
